_wandb:
    value:
        cli_version: 0.27.2
        e:
            k1ivd1rwmno2hxqrcvtji42nxsbzhpdt:
                email: donottouchifitworks@gmail.com
                executable: /usr/local/bin/python
                git:
                    commit: b9ff862bb1c1f2c7b85640b28a04cd9a31f11d7f
                    remote: https://github.com/ROKMCHQ-AITF/MarineRomance.git
                host: 488010c3de1e
                os: Linux-5.15.0-97-generic-x86_64-with-glibc2.35
                program: <python with no main file>
                python: CPython 3.10.15
                root: /home/elicer/MarineRomance
                startedAt: "2026-06-14T14:47:24.759181Z"
                writerId: k1ivd1rwmno2hxqrcvtji42nxsbzhpdt
        m: []
        python_version: 3.10.15
        t:
            "3":
                - 2
                - 13
                - 15
                - 16
            "4": 3.10.15
            "5": 0.27.2
            "12": 0.27.2
            "13": linux-x86_64
augment:
    value:
        freq_mask: 24
        gain: false
        gain_range:
            - 0.6
            - 1.4
        mixup: 0
        mixup_mode: max
        noise: false
        noise_amp: 0.005
        spec_augment: false
        time_mask: 40
data:
    value:
        audio_dir: input/train_audio
        crop: random
        duration: 5
        folds_csv: input/folds.csv
        group_col: null
        id_col: filename
        label_col: primary_label
        multilabel: true
        sample_rate: 32000
        train_csv: input/train_metadata.csv
debug:
    value: false
exp_name:
    value: exp001_baseline
feature:
    value:
        channel_mode: repeat
        compute_on: gpu
        fmax: 16000
        fmin: 50
        hop_length: 320
        image_size:
            - 128
            - 128
        n_channels: 3
        n_fft: 1024
        n_mels: 128
        normalize: true
        power: 2
        to_db: true
        type: melspec
        win_length: 1024
loss:
    value:
        focal_gamma: 2
        label_smoothing: 0
        type: bce
metric:
    value:
        mode: max
        monitor: val_f1
        name: f1
model:
    value:
        backbone: tf_efficientnet_b0_ns
        drop_path_rate: 0.2
        drop_rate: 0.2
        head: linear
        in_chans: 3
        num_classes: 50
        pretrained: true
optimizer:
    value:
        lr: 0.001
        min_lr: 1e-06
        scheduler: cosine
        type: adamw
        warmup_ratio: 0.1
        weight_decay: 0.0001
seed:
    value: 42
train:
    value:
        amp: true
        batch_size: 32
        clip_grad: null
        epochs: 10
        folds:
            - 0
        grad_accum: 1
        n_folds: 5
        num_workers: 4
wandb:
    value:
        entity: null
        mode: online
        project: Navy-Marine-ai-contest
        tags:
            - baseline
            - 1fold
